### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by zteeed** [Headorteil/Discord_Emote_Bot#2]
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

> Maximum Line Length
>
> Limit all lines to a maximum of 79 characters.
>
> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

**Comment by zteeed** [comment]
T'as plus de marge

**Comment by Headorteil** [comment]
C'est super magnifique maintenant t'as vu
